version: "3.5"
services:
  trpg-web:
    image: trpg
    container_name: trpg-web
    restart: always
    ports:
      - 2100:2100
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      VBOT: "${VBOT}"
      VPASS: "${VPASS}"
      PORT: "${PORT}"
      SERVER_RECAPTCHA: "${SERVER_RECAPTCHA}"
      MAILSERVER: "${MAILSERVER}"
    volumes:
      - ./dist:/dist
    depends_on:
      - trpg-db
  trpg-db:
    image: mysql:8.0
    container_name: trpg-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ./mysql/data:/var/lib/mysql
